/*
 * TargetData.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package ontology.lowerOntology;



/**
 *  Java class for concept Target of SmartHouseOntology ontology.
 */
public abstract class TargetData	extends LocationObject implements nuggets.INugget
{
	//-------- constants ----------

	//-------- attributes ----------

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>Target</code>.
	 */
	public TargetData()  { //
	}

	//-------- accessor methods --------

	//-------- object methods --------

	/**
	 *  Get a string representation of this Target.
	 *  @return The string representation.
	 */
	public String toString() {
		return "Target("
		+ "location="+getLocation()
           + ")";
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this Target using the nuggets utility.
	 * @param c 
	 */
	public void _persist(nuggets.ICruncher c) {
		// declare references
		int idLocation = c.declare(location);
		// persist the nugget
		c.startConcept(this);
		if (idLocation>0) 
			c.put("location", idLocation);
	}
	
	/**
	 * Restore this Target 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	public void _set(String a, Object v) { //
		location =  (Location)v; 
	}
}
