/*
 * $class.javaName.java
 *
 * Generated by Protege plugin Beanynizer. 
 * This class implements the functionality of IndoorSpace.
 * Feel free to change.
 *
 */
package smarthouse.ontology.beanynizer;


/**
 *  Editable Java class for concept <code>IndoorSpace</code> of SmartHouseOntology ontology.
 */
public class IndoorSpace  extends IndoorSpaceData implements nuggets.INugget
{
  //-------- constructors --------

  /** 
   *  Default Constructor. <br>
   *  Create a new <code>IndoorSpace</code>.
   */
  public IndoorSpace() {
    // Empty constructor required for JavaBeans (do not remove).
  }

  /** 
   *  Init Constructor. <br>
   *  Create a new <code>IndoorSpace</code>.
   * @param instancename    
   */
  public IndoorSpace(String instancename) {
    // Constructor using required slots (change if desired).
    setInstanceName(instancename);
  }


  /** 
   *  Clone Constructor. <br>
   *  Create a new <code>IndoorSpace</code>.<br>
   *  Copy all attributes from <code>proto</code> to this instance.
   *
   *  @param proto The prototype instance.
   */
  public IndoorSpace(IndoorSpace proto) {
    setInstanceName(proto.getInstanceName());
  }

  //-------- custom code --------
  
  
  //-------- Object methods -----
  
  /**
   *  Get a string representation of this <code>IndoorSpace</code>.
   *  @return The string representation.
   */
  public String toString() {
    return "IndoorSpace("
         + "instancename="+getInstanceName()
         + ")";
  }
  
  /** 
   *  Get a clone of this <code>IndoorSpace</code>.
   *  @return a shalow copy of this instance.
   */
  public Object clone() {
    return new IndoorSpace(this);
  }
  
  /** 
   *  Test the equality of this <code>IndoorSpace</code> 
   *  and an object <code>obj</code>.
   *
   *  @param obj the object this test will be performed with
   *  @return false if <code>obj</code> is not of <code>IndoorSpace</code> class,
   *          true if all attributes are equal.   
   */
  public boolean equals(Object obj) {
    if (obj instanceof IndoorSpace) {
      IndoorSpace cmp=(IndoorSpace)obj;
      if (getInstanceName()!=cmp.getInstanceName() &&
           (getInstanceName()==null || !getInstanceName().equals(cmp.getInstanceName()))
          ) return false;
      return true;
    }
    return false;
  }
}

