/*
 * $class.javaName.java
 *
 * Generated by Protege plugin Beanynizer. 
 * This class implements the functionality of ChildrenRoom.
 * Feel free to change.
 *
 */
package ontology.lowerOntology;


/**
 *  Editable Java class for concept <code>ChildrenRoom</code> of SmartHouseOntology ontology.
 */
public class ChildrenRoom  extends ChildrenRoomData implements nuggets.INugget
{
  //-------- constructors --------

  /** 
   *  Default Constructor. <br>
   *  Create a new <code>ChildrenRoom</code>.
   */
  public ChildrenRoom() {
    // Empty constructor required for JavaBeans (do not remove).
  }

  /** 
   *  Init Constructor. <br>
   *  Create a new <code>ChildrenRoom</code>.
   * @param instancename    
   */
  public ChildrenRoom(String instancename) {
    // Constructor using required slots (change if desired).
    setInstanceName(instancename);
  }


  /** 
   *  Clone Constructor. <br>
   *  Create a new <code>ChildrenRoom</code>.<br>
   *  Copy all attributes from <code>proto</code> to this instance.
   *
   *  @param proto The prototype instance.
   */
  public ChildrenRoom(ChildrenRoom proto) {
    setInstanceName(proto.getInstanceName());
  }

  //-------- custom code --------
  
  
  //-------- Object methods -----
  
  /**
   *  Get a string representation of this <code>ChildrenRoom</code>.
   *  @return The string representation.
   */
  public String toString() {
    return "ChildrenRoom("
         + "instancename="+getInstanceName()
         + ")";
  }
  
  /** 
   *  Get a clone of this <code>ChildrenRoom</code>.
   *  @return a shalow copy of this instance.
   */
  public Object clone() {
    return new ChildrenRoom(this);
  }
  
  /** 
   *  Test the equality of this <code>ChildrenRoom</code> 
   *  and an object <code>obj</code>.
   *
   *  @param obj the object this test will be performed with
   *  @return false if <code>obj</code> is not of <code>ChildrenRoom</code> class,
   *          true if all attributes are equal.   
   */
  public boolean equals(Object obj) {
    if (obj instanceof ChildrenRoom) {
      ChildrenRoom cmp=(ChildrenRoom)obj;
      if (getInstanceName()!=cmp.getInstanceName() &&
           (getInstanceName()==null || !getInstanceName().equals(cmp.getInstanceName()))
          ) return false;
      return true;
    }
    return false;
  }
}

