/*
 * LocationObjectData.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package ontology.lowerOntology;



/**
 *  Java class for concept LocationObject of SmartHouseOntology ontology.
 */
public abstract class LocationObjectData implements nuggets.INugget
{
	//-------- constants ----------

	//-------- attributes ----------

	/** The location of the object. */
	protected  Location  location;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>LocationObject</code>.
	 */
	public LocationObjectData()  { //
	}

	//-------- accessor methods --------

	/**
	 *  Get the location of this LocationObject.
	 *  The location of the object.
	 * @return location
	 */
	public Location  getLocation() {
		return this.location;
	}

	/**
	 *  Set the location of this LocationObject.
	 *  The location of the object.
	 * @param location the value to be set
	 */
	public void  setLocation(Location location) {
		this.location = location;
	}

	//-------- object methods --------

	/**
	 *  Get a string representation of this LocationObject.
	 *  @return The string representation.
	 */
	public String toString() {
		return "LocationObject("
		+ "location="+getLocation()
           + ")";
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this LocationObject using the nuggets utility.
	 * @param c 
	 */
	public void _persist(nuggets.ICruncher c) {
		// declare references
		int idLocation = c.declare(location);
		// persist the nugget
		c.startConcept(this);
		if (idLocation>0) 
			c.put("location", idLocation);
	}
	
	/**
	 * Restore this LocationObject 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	public void _set(String a, Object v) { //
		location =  (Location)v; 
	}
}
