/*
 * ContextEntityData.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package ontology.lowerOntology;



/**
 *  Java class for concept ContextEntity of SmartHouseOntology ontology.
 */
public abstract class ContextEntityData implements nuggets.INugget
{
	//-------- constants ----------

	//-------- attributes ----------

	/** Attribute for slot instanceName. */
	protected  String  instancename;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>ContextEntity</code>.
	 */
	public ContextEntityData()  { //
	}

	//-------- accessor methods --------

	/**
	 *  Get the instanceName of this ContextEntity.
	 * @return instanceName
	 */
	public String  getInstanceName() {
		return this.instancename;
	}

	/**
	 *  Set the instanceName of this ContextEntity.
	 * @param instancename the value to be set
	 */
	public void  setInstanceName(String instancename) {
		this.instancename = instancename;
	}

	//-------- object methods --------

	/**
	 *  Get a string representation of this ContextEntity.
	 *  @return The string representation.
	 */
	public String toString() {
		return "ContextEntity("
		+ "instancename="+getInstanceName()
           + ")";
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this ContextEntity using the nuggets utility.
	 * @param c 
	 */
	public void _persist(nuggets.ICruncher c) {
		// declare references
		// persist the nugget
		c.startConcept(this);
		if (instancename!=null) 
			c.put("instancename", instancename);
	}
	
	/**
	 * Restore this ContextEntity 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	public void _set(String a, Object v) { //
		instancename =  (String)v; 
	}
}
